#!/usr/bin/python3
def safe_print_list(my_list=[], x=0):
    i = 0
    try:
        for a in my_list[:x]:
            print("{}".format(a), end="")
            i += 1
        print()

    except:
        print("error")

    return i